### ISSUE TITLE
ProMix

### ISSUE THREAD

**Issue by nengwp** [LanXiaoPang613/C2MT#1]
There is no comparison between ProMix and the ProMix method in this paper. The ProMix method appears to be more effective.

**Comment by LanXiaoPang613** [comment]
Yes, ProMix is a great framework for LNL. Our framework is an improvement based on dividemix, and the key process is the proposed c2m strategy, which can theoretically be embedded in existing SSL based sample selection framework that uses a dual model, as long as that framework uses a co-teaching structure. Thank you for your comments.

**Comment by nengwp** [comment]
Thank you for your prompt reply! Your workflow is inspiring to me, but for higher performance, is it possible to incorporate ProMix's sample selection strategy?

**Comment by LanXiaoPang613** [comment]
I can't give you a definite answer, but I think you can try. I actually hadn't seen proMix at the wariting time of this study. I learned promix's framework later, and I think it's very sophisticated and complex, but I'm not sure if our c2m strategy is up to it.

**Comment by LanXiaoPang613** [comment]
If this work is useful for you or your team, please give us a star and cite this work. thank you.

**Comment by nengwp** [comment]
There are many ProMix strategies. I've recently been learning and applying it to my own data set. It is difficult to merge your excellent work with ProMix. But it might be useful to use some of these submodules or ideas. Of course, the star Yes!
